# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from chatbot import *
from pcha import *
import mysql.connector
from sys import *
class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-31, -21, 1491, 941))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 175, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(340, 100, 461, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0))")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(360, 270, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0))\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(480, 280, 281, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(480, 360, 281, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(360, 350, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0))\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(560, 410, 121, 31))
        self.label_5.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0))")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(680, 420, 61, 16))
        self.pushButton.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));\n"
"border-radius:2px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_56 = QtWidgets.QPushButton(self.frame)
        self.pushButton_56.setGeometry(QtCore.QRect(530, 460, 101, 41))
        self.pushButton_56.setStyleSheet("background:rgb(162, 255, 249);\n"
"border-radius:20px;\n"
"")
        self.pushButton_56.setObjectName("pushButton_56")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(350, 540, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login here"))
        self.label_2.setText(_translate("MainWindow", "User Name :"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "enter your username"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "enter your password"))
        self.label_3.setText(_translate("MainWindow", "  password :"))
        self.label_5.setText(_translate("MainWindow", "forgotten password                              "))
        self.pushButton.setText(_translate("MainWindow", "click here"))
        self.pushButton_56.setText(_translate("MainWindow", "LOGIN"))
    def chatbot(self):
             s=self.lineEdit.text()
             v=self.lineEdit_2.text()
             self.lineEdit.setText("")
             self.lineEdit_2.setText("")
             if(len(s)==0 or len(v)==0):
                 self.label_4.setText("Please fill all the inputs")
             else:    
              myconn = mysql.connector.connect(host = "localhost", user = "root",password = "",database="chatbot")
              cur=myconn.cursor()
             
              cur.execute('select mail_id from chatbot1')
              names=cur.fetchall()
              myconn.close()
              l=len(names)
              for i in range(0,l):
                 if(names[i][0]==s):
                   myconn = mysql.connector.connect(host = "localhost", user = "root",password = "",database="chatbot")
                   cur=myconn.cursor()
                   sql='select password from chatbot1 where mail_id= %s '
                   val=[(s)]
                   cur.execute(sql,val)
                   res=cur.fetchone()
                   myconn.close()
                   if(res[0]==v):
             
                    self.chatbot=QtWidgets.QMainWindow()
                    self.ui=Ui_MainWindow4()
                    self.ui.setupUi(self.chatbot)
                    self.chatbot.show()
                    self.ui.pushButton.clicked.connect(self.ui.seet)
                    self.ui.pushButton_2.clicked.connect(self.ui.exi)
                    break
                   else:
                    self.label_4.setText(" PASSWORD IS WRONG")
                    break
              else:
                 self.label_4.setText("USERNAME  and password notfound")
    def paschange(self):
        self.pcha=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow21()
        self.ui.setupUi(self.pcha)
        self.pcha.show()
        self.ui.pushButton.clicked.connect(self.ui.pcha)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton_56.clicked.connect(ui.chatbot)
    ui.pushButton.clicked.connect(ui.paschange)
    sys.exit(app.exec_())
